### ISSUE TITLE
[Android] - Build error with react-native 0.69.1

### ISSUE THREAD

**Issue by Zestpond** [mattermost/react-native-paste-input#10]
`./node_modules/@mattermost/react-native-paste-input/android/src/main/java/com/mattermost/pasteinput/PasteInputEditText.kt: (43, 48): Type mismatch: inferred type is InputConnection? but InputConnection was expected
`

RN: 0.69.1
@mattermost/react-native-paste-input: 0.4.2

**Comment by enahum** [comment]
Can you try the newest version?

**Comment by matlin** [comment]
We're also having issues building with RN 0.69.6 on Android

**Comment by shahbazmustafa-invozone** [comment]
I am also still facing the same issue.

**Comment by ikjnv** [comment]
I'm also getting the same issue. Tried <b>v0.3.4</b>, <b>v0.3.6</b> and <b>v0.5.1</b>

React Native: <b>v0.66.3</b>, <b>v0.67.2</b>

**Comment by ikjnv** [comment]
@v-olishynskyi not yet. Still facing the same issue.
