### ISSUE TITLE
Android Not Working

### ISSUE THREAD

**Issue by timothyerwin** [mattermost/react-native-paste-input#24]
Do I need to do anything extra to configure Android? 

It works fine in iOS, but then when I try to do the keyboard gif, or paste an image from clipboard it just says "Can't enter this content here" or the image just prints weird characters with `Exif` at the end...

I'm guessing it's not actually running the Android code or I need to install something else in the Gradle?

**Comment by timothyerwin** [comment]
I tried running the example itself on my native samsung galaxy and it fails as well.

![Screenshot_20230825_170514_ReactNativePasteInput Example](https://github.com/mattermost/react-native-paste-input/assets/2653209/0da425cf-edbc-4772-91eb-3b3262bad76c)

**Comment by enahum** [comment]
What version of Android are you on?

**Comment by timothyerwin** [comment]
I found out it works with GBoard but not the default Samsung keyboard. I'm trying this solution mentioned here now but not sure if it works yet...

https://github.com/mattermost/react-native-paste-input/issues/8

**Comment by timothyerwin** [comment]
@enahum it works perfectly with both keyboards after applying #8 

maybe you could do an update?

**Comment by enahum** [comment]
> @enahum it works perfectly with both keyboards after applying #8 
> 
> 
> 
> maybe you could do an update?

Great.. can you submit a PR?, I'll make sure to review/merge and release during the weekend

**Comment by timothyerwin** [comment]
> > @enahum it works perfectly with both keyboards after applying #8
> > maybe you could do an update?
> 
> Great.. can you submit a PR?, I'll make sure to review/merge and release during the weekend

I can but I also want to include this fix:

```
#import "react_native_paste_input/react_native_paste_input-Swift.h"
```

But I don't know if that will break it for anyone else. Do you know the `#if` block conditions around that?

**Comment by enahum** [comment]
No i dont but I think adding a */* at the end should be enough to handle everything else
