### ISSUE TITLE
[IOS Only] Error: Argument appears to not be a ReactComponent. Keys: clear,isFocused,focus,blur

### ISSUE THREAD

**Issue by tronginc** [mattermost/react-native-paste-input#5]
Is it similar to RNTextInput?
I have to try this lib with `react-native-ui-lib`, but it doesn't work :(.

I got this error:
`Error: Argument appears to not be a ReactComponent. Keys: clear,isFocused,focus,blur`

```tsx
import React, { useRef } from 'react';
import { TextInput } from 'react-native';
import PasteInput, { PastedFile, PasteInputRef } from "@mattermost/react-native-paste-input";
import { Keyboard } from 'react-native-ui-lib';

const YourTextInput = () => {
    const inputRef = useRef<PasteInputRef>(null);

    const onPaste = (
        error: string | null | undefined,
        files: Array<PastedFile>
    ) => {
        console.log('ERROR', error);
        console.log('PASTED FILES', files);
    };

    return (
      <Keyboard.KeyboardAccessoryView
              useSafeArea={true}
              addBottomView={true}
              renderContent={() => (
                 <PasteInput
                    ref={inputRef}
                    disableCopyPaste={false}
                    onPaste={onPaste}
                    multiline={true}
                    blurOnSubmit={false}
                    underlineColorAndroid="transparent"
                    keyboardType="default"
                    disableFullscreenUI={true}
                    textContentType="none"
                    autoCompleteType="off"
                />
                /* <TextInput
                    ref={inputRef}
                    multiline={true}
                    blurOnSubmit={false}
                    underlineColorAndroid="transparent"
                    keyboardType="default"
                    disableFullscreenUI={true}
                    textContentType="none"
                    autoCompleteType="off"
                /> */
              )}
              kbInputRef={inputRef}
              kbComponent={kbComponent}
              onItemSelected={onCustomKeyboardItemPressed}
            />       
    );
}
```

**Comment by enahum** [comment]
Does the example app work for you? What is your react and react-native version?

This should be a drop replacement for RNTextInput.

I can take a look in a few hours but it would be good if you can provide the answers to my questions ;)

**Comment by tronginc** [comment]
Thank you for quick response.
The problem may be could not `findNodeHandle` of it's ref.

[https://github.com/facebook/react-native/blob/feae814153783a0d03d0a332917991f139c36e9f/Libraries/Renderer/implementations/ReactNativeRenderer-dev.fb.js#L23340](https://github.com/facebook/react-native/blob/feae814153783a0d03d0a332917991f139c36e9f/Libraries/Renderer/implementations/ReactNativeRenderer-dev.fb.js#L23340)

I think the `inputRef` is missing `_nativeTag` property like `RNTextInput`.

**Comment by tronginc** [comment]
The problem is resolved! I have edited this method and it works. Thank you.

https://github.com/mattermost/react-native-paste-input/blob/03627dbf04d41ab39593ce7399cdb9ba9fdac547/src/index.tsx#L205

```tsx
useImperativeHandle(
    ref,
    () => ({
        clear,
        isFocused,
        focus: () => inputRef.current?.focus(),
        blur: () => inputRef.current?.blur(),
        ...(inputRef.current || {}) <-- here
    }),
    [clear]
);
```

**Comment by enahum** [comment]
Would you please submit a PR so it is fixed upstream? Thanks

**Comment by tronginc** [comment]
> Would you please submit a PR so it is fixed upstream? Thanks

Yes, please. It's #6. Thank you.
